FROM openjdk:17-jdk

ENV SPRING_PROFILE=dev

ARG JAR_FILE=build/libs/gongkademy-back-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} gongkademy.jar

CMD ["java", "-jar", "-Dspring.profiles.active=${SPRING_PROFILE}", "-Duser.timezone=Asia/Seoul", "gongkademy.jar"]